apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
    type: NodePort
    selector:
        app: sample-app
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP