// pipeline {
//     agent any
//     enviroment {
//         str = 'hello'
//     }

//     stages {
//         stage('Build') {
//             steps {
//                 sh (script: """
//                     echo "Building..."
//                     git clone https://github.com/vking34/devops-references.git
//                     cd ./devops-references/ci-cd/sample-app/
                    
//                     docker build . -t sample-app:2.0
//                     """)
//             }
//         }

//         stage('Test') {
//             steps {
//                 sh(script: """
//                 echo "Done!"
//                 """)
//             }
//         }
//     }
// }


node('jenkins-slave') {

    def tag = env.GIT_COMMIT

    stage('Fetch'){
        sh (script: """
        echo "Fetching..."
        git clone https://github.com/vking34/devops-references.git
        cd ./devops-references/ci-cd/sample-app/

        """)
    }

    stage('Build') {
        sh (script: """
        echo "Building..."
        docker build . -t vking34/sample-app:${tag}
        """)
    }
    
    stage('Test') {
        sh(script: """
        echo "Done!"
        """)
    }

    stage('Delivery'){

    }
}