node('jenkins-slave') {
    
     stage('test pipeline') {
        sh(script: """
        echo "hello"
        git clone https://github.com/vking34/devops-references.git
        cd ./cicd/sample-app/
        
        docker build . -t sample-app:1.1
        echo "done!"
        """)
    }
}